### ISSUE TITLE
Grails 3 version

### ISSUE THREAD

**Issue by micke-a** [turboDi/grails-likeable#3]
Hi

Are you still active within the Grails eco system? 
Asking because I'm using the likeable plugin in a Grails2 application and have recently started to review plugins to see if what I'm using is available for Grails3.

If you're still active it would be interesting to see if you've been thinking about migrating the likeable plugin and what effort is involved.

Thanks for a plugin which I found very usable!

Cheers,
Mikael

**Comment by turboDi** [comment]
Hi @micke-a! 

Sorry for a delay (didn't expect any activity here tbh). 
Glad that you liked the plugin, but I don't have any plans to migrate it to Grails 3 as I stopped to use Grails a while ago and haven't tried version 3 at all (and there is 4th version already). 

If I understood [this guide](http://docs.grails.org/3.0.x/guide/upgrading.html) correctly, to make this plugin work with Grails 3-4 one should create a completely new plugin with either a new repository or dedicated branch. This should be pretty straightforward, but needs involvement in Grails world, that I don't have anymore, sorry

So if you still need it, I can try to assist by either reviewing your PR or giving you access to this repo. Thanks for your feedback and I wish you all the best!

**Comment by micke-a** [comment]
Hiya
In the end I decided to not migrate to off grails2 and keep the app as-is, was quite a bit of work and a lot of plugins I use weren't migrated.

Thanks for checking in though and all the best,
Micke
